apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk3010
  namespace: skala3-ai1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: amdp-registry.skala-ai.com/skala26a-ai1/a3010-skala-stock-api@sha256:be86f76be31a830e45862ac24d4f36a4a27c9e48c2d446db42c037c9df475121
        ports:
        - containerPort: 8080
